services:
  # Descomentar cuando se ejecute el backend tambien 
  # app:
  #   build:
  #     context: ./Backend/Backend
  #     target: final
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - .env.development
  #   depends_on:
  #     - postgresql
  #     - mongodb
  #     - redis
  #     - clickhouse
  #     - elasticsearch

  # admin:
  #   build:
  #     context: ./Backend/Admin
  #   ports:
  #     - "${DJANGO_PORT:-8000}:8000"
  #   env_file:
  #     - .env.development
  #   depends_on:
  #     - postgresql
  #     - mongodb
  #     - clickhouse

  
  postgresql:
    image: postgres:17
    container_name: postgresql_db
    restart: always
    env_file:
      - .env.development
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./Databases/postgresql/restore.sh:/docker-entrypoint-initdb.d/restore.sh
      - ./Databases/postgresql/backup.sql:/tmp/backup.sql
      - ./Databases/postgresql/volumen:/var/lib/postgresql/data

  mongodb:
    image: mongo:8
    container_name: mongodb_db
    restart: always
    env_file:
      - .env.development
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./Databases/mongoDB/init.js:/docker-entrypoint-initdb.d/init.js
      - ./Databases/mongoDB/volumen:/data/db

  redis:
    image: redis:8
    container_name: redis_db
    restart: always
    command: /bin/sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
    env_file:
      - .env.development
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./Databases/redis/volumen:/data

  clickhouse:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse_db
    restart: always
    env_file:
      - .env.development
    ports:
      - "${CLICKHOUSE_PORT:-8123}:8123"
      - "${CLICKHOUSE_HTTP_PORT:-8124}:8124"
    volumes:
      - ./Databases/ClickHouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Databases/ClickHouse/volumen:/var/lib/clickhouse

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch_db
    restart: always
    env_file:
      - .env.development
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
    volumes:
      - ./Databases/elasticsearch/volumen:/usr/share/elasticsearch/data
