/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/Auth/registro': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['RegistroRequestDto'];
          'text/json': components['schemas']['RegistroRequestDto'];
          'application/*+json': components['schemas']['RegistroRequestDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/Auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['LoginRequestDto'];
          'text/json': components['schemas']['LoginRequestDto'];
          'application/*+json': components['schemas']['LoginRequestDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['UsuarioResponseDto'];
            'application/json': components['schemas']['UsuarioResponseDto'];
            'text/json': components['schemas']['UsuarioResponseDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/Auth/olvido-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['OlvidoPasswordRequestDto'];
          'text/json': components['schemas']['OlvidoPasswordRequestDto'];
          'application/*+json': components['schemas']['OlvidoPasswordRequestDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/Auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ResetPasswordRequestDto'];
          'text/json': components['schemas']['ResetPasswordRequestDto'];
          'application/*+json': components['schemas']['ResetPasswordRequestDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/Categoria': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/Producto': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          terminoBusqueda?: string;
          categorias?: number[];
          pagina?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ProductoResponseDto'][];
            'application/json': components['schemas']['ProductoResponseDto'][];
            'text/json': components['schemas']['ProductoResponseDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/Producto/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ProductoResponseDto'];
            'application/json': components['schemas']['ProductoResponseDto'];
            'text/json': components['schemas']['ProductoResponseDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/Producto/{id}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ResenasProductoResponseDto'];
            'application/json': components['schemas']['ResenasProductoResponseDto'];
            'text/json': components['schemas']['ResenasProductoResponseDto'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CrearResenaRequestDto'];
          'text/json': components['schemas']['CrearResenaRequestDto'];
          'application/*+json': components['schemas']['CrearResenaRequestDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ComentarioDto: {
      nombreUsuario?: string | null;
      /** Format: int32 */
      calificacion?: number;
      comentario?: string | null;
      /** Format: date-time */
      fecha?: string;
    };
    CrearResenaRequestDto: {
      /** Format: int32 */
      calificacion: number;
      comentario: string;
    };
    DistribucionEstrellasDto: {
      /** Format: int32 */
      cincoEstrellas?: number;
      /** Format: int32 */
      cuatroEstrellas?: number;
      /** Format: int32 */
      tresEstrellas?: number;
      /** Format: int32 */
      dosEstrellas?: number;
      /** Format: int32 */
      unaEstrella?: number;
    };
    LoginRequestDto: {
      email?: string | null;
      password?: string | null;
    };
    OlvidoPasswordRequestDto: {
      email?: string | null;
    };
    ProductoResponseDto: {
      /** Format: int32 */
      idProducto?: number;
      nombre?: string | null;
      descripcion?: string | null;
      /** Format: double */
      precioBase?: number;
      /** Format: double */
      precioAplicado?: number;
      urlImagen?: string | null;
      /** Format: int32 */
      stock?: number;
      /** Format: double */
      porcentajeDescuentoFlash?: number;
      /** Format: int32 */
      idCategoria?: number;
      categoria?: string | null;
      nombreVendedor?: string | null;
      /** Format: double */
      estrellas?: number;
      /** Format: int32 */
      cantidadReviews?: number;
    };
    RegistroRequestDto: {
      nombre?: string | null;
      apellido?: string | null;
      email?: string | null;
      password?: string | null;
      telefono?: string | null;
      direccion?: string | null;
    };
    ResenasProductoResponseDto: {
      /** Format: double */
      promedioEstrellas?: number;
      /** Format: int32 */
      totalReviews?: number;
      distribucion?: components['schemas']['DistribucionEstrellasDto'];
      comentarios?: components['schemas']['ComentarioDto'][] | null;
    };
    ResetPasswordRequestDto: {
      token?: string | null;
      nuevoPassword?: string | null;
    };
    UsuarioResponseDto: {
      /** Format: int32 */
      idUsuario?: number;
      /** Format: int32 */
      idRol?: number;
      nombre?: string | null;
      apellido?: string | null;
      email?: string | null;
      telefono?: string | null;
      direccionPrincipal?: string | null;
      /** Format: date-time */
      fechaRegistro?: string;
      token?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
